component: scf
name: nodejs-runtime-demo

inputs:
  name: nodejs-runtime-demo
  src:
    src: ./dist
    exclude:
      - .env
  region: ap-guangzhou
  runtime: Nodejs12.16
  handler: index.handler
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: ANY
              function:
                isIntegratedResponse: true
                functionQualifier: $DEFAULT
